FROM python:3.6.1

LABEL NAME {{ cookiecutter.project_name }}
LABEL VERSION {{ cookiecutter.version }}

MAINTAINER {{cookiecutter.full_name}} {{cookiecutter.email}}

# set working directory to /usr/src/
WORKDIR /usr/src/