# Docker Compose
# https://docs.docker.com/compose/

version: "3"
services:
  # Python
  app:
    environment: &environment
      - STAGE=local
    image: {{ cookiecutter.project_name }}-app-dev:{{ version }}
    build:
      args:
        stage: dev

  check:
    image: {{ cookiecutter.project_name }}-check-dev:{{ version }}
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env
